### ISSUE TITLE
API Design: Interior mutability?

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/gerber-rs#1]
There are two approaches to designing the API:

## Following standard mutability rules

There are some thing we need to take care of at a "project" level (e.g. handing out non-colliding ids for apertures). So we should have a Project struct.

```rust
let mut project = Project::new();
```

We can now create a layer and add it to the project:

```rust
let mut layer = Layer::new();
project.add_layer(layer);
```

The problem is with apertures though. I'd like to work with "aperture objects", but apertures need to be managed at project level.

```rust
let aperture1 = project.create_aperture(Aperture::Circle(Circle::new(1.0)));
```

The thing is that if we return an Aperture instance, we still don't have a reference to it from the Project. And if we store the aperture inside the project and return a reference, we'll end up with multiple mutable references.

We could of course just work with integers to reference apertures, but then we lose all type safety.

There would probably be a way to work around this issue, but the ergonomics are probably bad.

## Interior mutability

There could be an alternative approach.

A project could keep track of all layers using reference counting with a `Rec<Rc<Layer>>`.

```rust
pub struct Project {
    layers: Vec<Rc<Layer>>,
}

impl Project {
    pub fn new() -> Self {
        Project { layers: vec![] }
    }

    pub fn create_layer(&mut self) -> Rc<Layer> {
        let layer = Rc::new(Layer::new());
        self.layers.push(layer.clone());
        layer
    }
}
```

This allows us to keep a reference to the layer while handing out another reference. A `Rc` doesn't allow mutation though, so if we want the layer to be modifiable we need to use `RefCell`.

```rust
struct Layer {
    file_attributes: RefCell<Vec<types::FileAttribute>>,
}

impl Layer {
    pub fn new() -> Self {
        Layer { file_attributes: RefCell::new(vec![]) }
    }

    pub fn set_file_attribute(&self, attribute: types::FileAttribute) {
        self.file_attributes.borrow_mut().push(attribute);
    }
}
```

This is nice and will never panic as long as we never hand out the `RefCell` to the caller and only mutate from methods.

The downside is that we can now mutate non-mut `Layer` instances which is a bit weird from an API point of view:

```rust
let mut project = Project::new();
let layer = project.create_layer();
layer.set_file_attribute(...);
```

Opinions? @rnestler

**Comment by ubruhin** [comment]
I have some questions:
- What is the `Project` type for?
- Why creating apertures on `Project` level instead of `Layer` level?
- Do the user needs to ensure by himself that there are no duplicate apertures (to keep the Gerber output as short as possible)? Let's say you have a PCB with 20 identical pads on it and want to export it as Gerber. Then it would be a mess to first determine which pads can be drawn using the same aperture and which not, it's much simpler to just iterate over all pads and create a new aperture for each pad. The Gerber library should be smart enough to remove duplicate apertures. Pseudo code:
```rust
for (pad in pads) {
  layer.flash(pad.x, pad.y, Aperture::new(Aperture::rect, pad.width, pad.height));
}
```

**Comment by dbrgn** [comment]
> What is the Project type for?

Hm, I actually mixed up layers and projects. A layer and a project can be merged. (I had in mind that multiple layers can be in a gerber file.)

Regarding your second question, that's a good point. We could try to make an aperture hashable, which would mean that we could use it as a key in a hashmap (with the value being the aperture code assigned by the layer). What do you think?

**Comment by ubruhin** [comment]
> We could try to make an aperture hashable

:+1: 

Another approach may be to completely hide apertures for the user. So the API would be more "graphics oriented" instead of "aperture oriented". The library would then create and use the apertures automatically depending on the parameters passed to the drawing functions. But I think this would make the library much more complicated and I'm not sure if it's worth the effort...

**Comment by dbrgn** [comment]
Yeah, I think that would be a wrong level of abstraction.

**Comment by dbrgn** [comment]
Without the `Project` type, we can get around the mutability issue for now:

https://github.com/dbrgn/gerber-rs/blob/master/examples/simple.rs (work in progress)
